### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by meherett** [buybackoff/SoltsiceExample#1]
$ npm run deploy

> soltsice-consumer@1.0.0 deploy C:\Users\HP\Desktop\SoltsiceExample
> tsc && node ./dist/test.js

C:\Users\HP\Desktop\SoltsiceExample\node_modules\soltsice\dist\src\W3.js:95
            throw 'Default W3 instance is not set. Use W3.Default setter.';
            ^
Default W3 instance is not set. Use W3.Default setter.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! soltsice-consumer@1.0.0 deploy: `tsc && node ./dist/test.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the soltsice-consumer@1.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2018-01-25T13_48_11_467Z-debug.log

**Comment by buybackoff** [comment]
The sample is somewhat outdated, you need to explicitly provide w3 instance to all methods or explicitly set the default static value as `W3.Default = yourW3Instance or new W3('http://...:8545')`. See the other linked repos (tests in dbrain-contracts first) for working samples. Also tests in https://github.com/buybackoff/SolidityAuction use Soltsice.
